### ISSUE TITLE
Code use / Pypi

### ISSUE THREAD

**Issue by Vyvra** [ChessSpider/dvsportal#4]
Hello,

I'm trying to build a python script to allow guests to send an email to register for their parking. For this I've been using your version of the DVSportal api. I would like to publish this script on github, with credit to you and tcoenraad for the DVSportal module. I just wanted to check if that is alright with you. 

Also it would be helpful if the Dvsportal module was a Pypi package. I saw that tcoenraad was not actively working on this because he moved. If you would be willing to put it on Pypi, I could write some documentation/examples for if that would be helpful. Please don't feel any pressure, it's just something that would be nice.   

Also thank you very much for writing the Homeassistant integration, I've been using it as my main way to register guests for a few months now.

**Comment by ChessSpider** [comment]
hi @Vyvra , happy to hear its working for you! 

Ive indeed been wanting to create a pypi package of dvsportal. I already have tcoenraad's permission https://github.com/tcoenraad/python-dvsportal/issues/3

ill try and prioritize it this weekend so you can continue development! Good luck

**Comment by Vyvra** [comment]
Thanks @ChessSpider for making that effort.

**Comment by ChessSpider** [comment]
hi @Vyvra , i did a really quick publish; see here: https://pypi.org/project/dvsportal/
