### ISSUE TITLE
Login portal Zwolle not working

### ISSUE THREAD

**Issue by 2Wanderer** [ChessSpider/dvsportal#5]
Hi, i'd tried to add this integration for the visitor potal in Zwolle to my home assistant, however the logs state that the login is was not succusfull and as such the integration wont install. 

HA errorlog: 
async step user (200, {'ErrorMessage': 'Het nummer of de pincode is incorrect.', 'LoginStatus': 2, 'Result': 0, 'RequiresOtp': False})
However, this is not the case.  I can login succesfull with the credentials when used directly the portal. We've been forced login with the cardnumber and the pincode https://parkeerloket.zwolle.nl/DVSportal

I try to understand whats going wrong here, as i'd like to use this integration.

**Comment by ChessSpider** [comment]
hi @2Wanderer ,

I just tried logging in on Zwolle's mediaportal, and I noticed the permitMediaTypeID is different:

![image](https://github.com/ChessSpider/dvsportal/assets/2168372/74061140-a558-4f06-b402-3308b145c63b)

in my code its set to 1: https://github.com/ChessSpider/dvsportal/blob/main/dvsportal/dvsportal.py#L148

That probably explains why your login doesnt work.

I hope to have some time this weekend to investigate

**Comment by ChessSpider** [comment]
hi @2Wanderer , ive tried something which maybe fixes it. Can you give it a try? Dont forget to update to latest version first 👍

**Comment by 2Wanderer** [comment]
I deleted the custom integration and readded the new version, did restart HA and tried to connect, no luck yet, 
errorcode: 

Deze fout is ontstaan door een aangepaste integratie.

Logger: root
Bron: custom_components/dvsportal/config_flow.py:63
integratie: dvsportal (documentation, issues)
First occurred: 16:41:31 (2 gebeurtenissen)
Laatst gelogd: 16:43:34

async step user (400, {'message': '<!DOCTYPE html>\r\n<html>\r\n <head>\r\n <title>Runtime Error</title>\r\n <meta name="viewport" content="width=device-width" />\r\n <style>\r\n body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}\r\n b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}\r\n H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }\r\n H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }\r\n pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n .marker {font-weight: bold; color: black;text-decoration: none;}\r\n .version {color: gray;}\r\n .error {margin-bottom: 10px;}\r\n .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }\r\n @media screen and (max-width: 639px) {\r\n pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n }\r\n @media screen and (max-width: 479px) {\r\n pre { width: 280px; }\r\n }\r\n </style>\r\n </head>\r\n\r\n <body bgcolor="white">\r\n\r\n <span><H1>Server Error in \'/\' Application.<hr width=100% size=1 color=silver></H1>\r\n\r\n <h2> <i>Runtime Error</i> </h2></span>\r\n\r\n <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">\r\n\r\n <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.\r\n <br><br>\r\n\r\n <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>\r\n\r\n <table width=100% bgcolor="#ffffcc">\r\n <tr>\r\n <td>\r\n <code><pre>\r\n\r\n&lt;!-- Web.Config Configuration File --&gt;\r\n\r\n&lt;configuration&gt;\r\n &lt;system.web&gt;\r\n &lt;customErrors mode=&quot;Off&quot;/&gt;\r\n &lt;/system.web&gt;\r\n&lt;/configuration&gt;</pre> </code>\r\n\r\n </td>\r\n </tr>\r\n </table>\r\n\r\n <br>\r\n\r\n <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>\r\n\r\n <table width=100% bgcolor="#ffffcc">\r\n <tr>\r\n <td>\r\n <code><pre>\r\n\r\n&lt;!-- Web.Config Configuration File --&gt;\r\n\r\n&lt;configuration&gt;\r\n &lt;system.web&gt;\r\n &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;\r\n &lt;/system.web&gt;\r\n&lt;/configuration&gt;</pre> </code>\r\n\r\n </td>\r\n </tr>\r\n </table>\r\n\r\n <br>\r\n\r\n </font>\r\n\r\n </body>\r\n</html>\r\n'})
async step user (200, {'message': '<!doctype html><html lang="nl" ng-app="app"><head><meta charset="utf-8"/><title data-ng-bind="title">Bezoekers App</title><base href="/DVSPortal/"><meta name="format-detection" content="telephone=no"><meta name="HandheldFriendly" content="true"><meta name="viewport" content="initial-scale=1,width=device-width"><script defer="defer" src="dist/412-88c2fcb57f3253c67ebe.js"></script><script defer="defer" src="dist/citypermit-1f148f5f3660ddbf8c7f.js"></script><link href="dist/citypermit.css" rel="stylesheet"><link href="content/klanten/zwolle/zwolle.css" rel="stylesheet"/><link href="content/klanten/zwolle/fav-icon.png?v=2" rel="apple-touch-icon"/><link href="content/klanten/zwolle/fav-icon.png?v=2" rel="shortcut icon"/></head><body><shell class="page"></shell><script src="app.env.js"></script></body></html>'})

**Comment by 2Wanderer** [comment]
No luck yet. re-added integration and tried to login, no joy.
error in HA logs:

Logger: root
Bron: custom_components/dvsportal/config_flow.py:63
integratie: DVSPortal ([documentation](https://github.com/chessspider/dvsportal#readme), [issues](https://github.com/ChessSpider/dvsportal/issues))
First occurred: 16:58:19 (1 gebeurtenissen)
Laatst gelogd: 16:58:19

async step user (400, {'message': '<!DOCTYPE html>\r\n<html>\r\n <head>\r\n <title>Runtime Error</title>\r\n <meta name="viewport" content="width=device-width" />\r\n <style>\r\n body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} \r\n p {font-family:"Verdana";font-weight:normal;color:black;margin-top:

**Comment by ChessSpider** [comment]
the last error is really odd to me. If I try it for parkeerloket.zwolle.nl; I see this in the logs, as expected as I dont have correct credentials:
```
async step user (200, {'ErrorMessage': 'Het nummer of de pincode is incorrect.', 'LoginStatus': 2, 'Result': 0, 'RequiresOtp': False})
```

Do you also enter `parkeerloket.zwolle.nl` as value for hostname?

**Comment by 2Wanderer** [comment]
I used parkeerloket.zwolle.nl/DVSPortal/ thats were it went wrong on my side. I retried it this morning with just  parkeerloket.zwolle.nl and It's working like a charm now. Thank you very much for this integration and your support! highly appriciated 👍

**Comment by ChessSpider** [comment]
great to hear! Enjoy :)
